#: import gch kivy.utils.get_color_from_hex
#: import raleway myfonts.fonts

#:set darkblue gch("023047")
#:set vlightblue gch("8ecae6")
#:set lightblue gch("219ebc")
#:set yellow gch("ffb703")
#:set orange gch("fb8500")
#:set darkblue gch("023047")

# fonts ---------------------------------------------------------------->
#:set bold raleway["Raleway"]['bold']
#:set regular raleway["Raleway"]['regular']
#:set semibold raleway["Raleway"]['semibold']


<FirstScreen>
